spring.application.name=reservation-system
spring.datasource.url=jdbc:postgresql://localhost:5432/rezervace
spring.datasource.username=rezervace
spring.datasource.password=rezervace

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true